apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local
resources:
  - ./postgres-configmap.yaml
  - ./postgres-pv.yaml
  - ./postgres-pvc.yaml
  - ./postgres-deployment.yaml
  - ./postgres-service.yaml
