[package]
name = "service"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain"}
repository = { path = "../repository"}
serde = { workspace = true }
thiserror = {workspace = true }
uuid = {workspace = true }

[lints]
workspace = true
