apiVersion: v1
kind: Service
metadata:
  name: allocations-rest-service
spec:
  selector:
    app: allocations-rest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
