[package]
name = "allocations-repository"
version = "0.1.0"
edition = "2024"

[dependencies]
allocations-domain = { path = "../domain"}
serde = { workspace = true }
sqlx = { workspace = true }
thiserror = {workspace = true }
uuid = {workspace = true }

[lints]
workspace = true
