[package]
name = "repository"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain"}
serde = { workspace = true }
sqlx = { workspace = true }
thiserror = {workspace = true }
uuid = {workspace = true }

[lints]
workspace = true
